name: Vulnerable Workflow Test

on:
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Process PR Metadata
        env:
          SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo "Processing PR title: ${{ github.event.pull_request.title }}"
          echo "Processing PR body: ${{ github.event.pull_request.body }}"
          # Example command that uses untrusted input
          curl -X POST -H "Authorization: Bearer $SECRET" -d "title=${{ github.event.pull_request.title }}" https://example.com/deploy


