name: Vulnerable Workflow

on:
  pull_request_target:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy Preview
        env:
          SECRET: ${{ secrets.MY_SECRET }}
        run: |
          # Using PR title in the command without sanitization
          curl -X POST -H "Authorization: Bearer $SECRET" -d "title=${{ github.event.pull_request.title }}" https://example.com/deploy

